#!/usr/bin/env python3
# -*- coding: utf-8 -*-

def main():
    dilution = input("[-] Enter dilution factor: ").strip()
    target_od = input("[-] Enter target OD: ").strip()
    total_vol = input("[-] Enter total volume in µL: ").strip()
    print("[!] Input OD values, 'print' to see all results, or blank to exit")
    measured_od = '0'
    results = []
    while measured_od is not None:
        measured_od = input("[>] Enter measured OD: ").strip()
        if measured_od is '':
            exit()
        elif measured_od == 'print':
            exit(print(str(results)))
        inoculum_vol = ((float(total_vol)*float(target_od))/float(measured_od))/float(dilution)
        broth_vol = int(total_vol)-int(inoculum_vol)
        print(f'[-] Inoculum: {int(inoculum_vol)}µL Broth: {int(broth_vol)}µL')
        results.append(f'{int(inoculum_vol)},{int(broth_vol)}')

if __name__ == '__main__':
    main()
